# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: "Visual Studio Dbuild"
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: "VS TS Test"
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: Docker@2
  displayName: "Docker Logout"
  inputs:
    containerRegistry: 'Docker Hub (hub.docker.com)'
    repository: 'geo-loc-api'
    command: 'logout'

- task: Docker@2
  displayName: "Docker Login"
  inputs:
    containerRegistry: 'Docker Hub (hub.docker.com)'
    repository: 'geo-loc-api'
    command: 'login'

- task: Docker@2
  displayName: "Docker Create Image & Push"
  inputs:    
    containerRegistry: 'Docker Hub (hub.docker.com)'
    repository: 'geo-loc-api'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)
